language: elixir
elixir: '1.7'
otp_release: '21.0'
env:
  matrix:
    secure: UwFC0AAs/fY1GhLQ6FDeRL0gxnO5vVWTyRWHyuoB3V1pJxq8YRW8sqNPJi3TBI7qJFHxOqmoktfxQeI0Rplx9edRtYDfczovV8WDRJBsKI5YCHVHBYzMkx9VLO+A1lUJoeESVtZP6N148XFXnMR7+2541HQxxJ0ZAU4roy08It19IUsxkQbCRmmnoZtxsKMFju+BhV6dI1b2qmFR8y9CCUP/Vbz0ysGW7u9pD3/g2nPNQlil1nnvjXnBVolyNbrk1EIBNbqBufLmIZ+qe/P/mjWC2zsAGAok2pxKmQqrOeCxIjKYsAKxRC6hO4hka+8nWmdbJEZEDsYwOJz7Bjq1UEoRZhVTm31FWmv/aP8ey8VGRO8NjHmLbMhnrx36PstBOXBmzTMjYToZ646Unrczqw7le6u+5fRvho7U1rJq2QDUaAcZKLLWLDaFtgrwkb4sWnXeYHceTbYv82NCvWwVVIBLfixpj76Va5RXtBUcq0aIELOPUzUshiyo3yKWbqzT7MD18PPYNAUtAd129Hfg2FZ5L5rrL+nGRrbHGTWTuj/dRMs1oe+ZZQfmT5Js8HqL5nP0tbvpp51vaYeRZY56itZVRRRS8Aa0EQkT40frKorrn1bO2JQL21l+OidSKRp+bHZlIaWUHJ8FjwtjZPEqkFy0Emtijiwbi9u2NTpFOA8=
